/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
}

dependencies {
    implementation(libs.jline)
    implementation(libs.kotlin.scripting.jvm)
    implementation(libs.kotlin.scripting.jvm.host)
    implementation(libs.kotlin.scripting.common)
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.AppKt"
}

tasks.withType<JavaExec> {
    standardInput = System.`in`
}